updated entrypoint

diff --git a/.github/workflows/test-all.yml b/.github/workflows/test-all.yml
--- a/.github/workflows/test-all.yml
+++ b/.github/workflows/test-all.yml
@@ -25,7 +25,7 @@ env:
       }
     }
 jobs:
-  # confirm we know how to properly escape the data that goes into set-output variables
+  # confirm we know how to properly escape the data that goes into set variables
   job-test-workflow-syntax:
     env:
       sample_var_0: '9'
@@ -91,63 +91,35 @@ jobs:
           100% complete
     runs-on: ubuntu-latest
     steps:
-      - name: Manually set-output variables
+      - name: Manually set variables
         id: manual-vars
         run: >
           sample_var_0="$( echo -e "${{ env.sample_var_0 }}" | sed -E 's/"/\\"/g' )";
           sample_var_1="$( echo -e "${{ env.sample_var_1 }}" | sed -E 's/"/\\"/g' )";
           sample_var_2="$( echo -e "${{ env.sample_var_2 }}" | sed -E 's/"/\\"/g' )";
           sample_var_3="$( echo -e "${{ env.sample_var_3 }}" | sed -E 's/"/\\"/g' )";
-          sed_command="$(
-            echo -e "
-                :nextLine;
-                # if not the end of the file
-                \$!{
-                  # add the next line to the pattern space
-                  N;
-                  # grab another line
-                  b nextLine;
-                }
-                # escape backslash characters
-                s/\\\\\\/\\\\\\\\\\\\\\/g;
 
-                # escape percentage sign
-                s/%/%25/g;
-
-                # esape newline characters
-                s/\\\n/%0A/g;
-                s/\\\r/%0D/g;
-
-                # escape double quotes
-                s/\\\"/\\\\\\\\\\\"/g;
-
-                # escape dollar sign
-                s/\\\\\$/\\\\\\\\\$/g;
-                ";
-              )";
-          echo "declared sed_command";
-
-          esc_sample_var_0="$( echo "${sample_var_0}" | sed -E "${sed_command}" || echo "SED COMMAND FAILED")";
+          esc_sample_var_0="$( echo "${sample_var_0}" | jq -sRr @uri || echo "JQ URI ENCODE OUTPUT FAILED")";
           echo "    sample_var_0:'${sample_var_0}'";
           echo "esc_sample_var_0:'${esc_sample_var_0}'";
-          echo "::set-output name=sample_var_0::${esc_sample_var_0}";
+          echo "sample_var_0=${esc_sample_var_0}" >> $GITHUB_OUTPUT;
 
-          esc_sample_var_1="$( echo "${sample_var_1}" | sed -E "${sed_command}" || echo "SED COMMAND FAILED")";
+          esc_sample_var_1="$( echo "${sample_var_1}" | jq -sRr @uri || echo "JQ URI ENCODE OUTPUT FAILED")";
           echo "    sample_var_1:'${sample_var_1}'";
           echo "esc_sample_var_1:'${esc_sample_var_1}'";
-          echo "::set-output name=sample_var_1::${esc_sample_var_1}";
+          echo "sample_var_1=${esc_sample_var_1}" >> $GITHUB_OUTPUT;
 
-          esc_sample_var_2="$( echo "${sample_var_2}" | sed -E "${sed_command}" || echo "SED COMMAND FAILED")";
+          esc_sample_var_2="$( echo "${sample_var_2}" | jq -sRr @uri || echo "JQ URI ENCODE OUTPUT FAILED")";
           echo "    sample_var_2:'${sample_var_2}'";
           echo "esc_sample_var_2:'${esc_sample_var_2}'";
-          echo "::set-output name=sample_var_2::${esc_sample_var_2}";
+          echo "sample_var_2=${esc_sample_var_2}" >> $GITHUB_OUTPUT;
 
-          esc_sample_var_3="$( echo "${sample_var_3}" | sed -E "${sed_command}" || echo "SED COMMAND FAILED")";
+          esc_sample_var_3="$( echo "${sample_var_3}" | jq -sRr @uri || echo "JQ URI ENCODE OUTPUT FAILED")";
           echo "    sample_var_3:'${sample_var_3}'";
           echo "esc_sample_var_3:'${esc_sample_var_3}'";
-          echo "::set-output name=sample_var_3::${esc_sample_var_3}";
+          echo "sample_var_3=${esc_sample_var_3}" >> $GITHUB_OUTPUT;
 
-      - name: Check manual set-output
+      - name: Check manual variables
         run: >
           sample_var_0="$( echo -e "${{ env.sample_var_0 }}" | sed -E 's/"/\\"/g' )";
           sample_var_1="$( echo -e "${{ env.sample_var_1 }}" | sed -E 's/"/\\"/g' )";
@@ -184,8 +156,8 @@ jobs:
 
       - name: Commit info
         run: >
-          echo "::set-output name=hash::$(git rev-parse HEAD)";
-          echo "::set-output name=name::$(git rev-parse --abbrev-ref HEAD)";
+          echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT;
+          echo "name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT;
 
       - name: Validate entrypoint
         uses: jadutter/jq-action@hotfix/patch-action
@@ -310,74 +282,46 @@ jobs:
             exit 1
           fi
 
-      - name: Manually set-output variables
+      - name: Manually set variables
         uses: jadutter/jq-action@develop
         id: manual-vars-jq
         with:
           cmd: >
             echo "declared data='${data}'";
-            sed_command="$( 
-              echo -e "
-                  :nextLine;
-                  # if not the end of the file
-                  \$!{
-                    # add the next line to the pattern space
-                    N;
-                    # grab another line
-                    b nextLine;
-                  }
-                  # escape backslash characters
-                  s/\\\\\\/\\\\\\\\\\\\\\/g;
-
-                  # escape percentage sign
-                  s/%/%25/g;
-
-                  # esape newline characters
-                  s/\\\n/%0A/g;
-                  s/\\\r/%0D/g;
-
-                  # escape double quotes
-                  s/\\\"/\\\\\\\\\\\"/g;
-
-                  # escape dollar sign
-                  s/\\\\\$/\\\\\\\\\$/g;
-                  ";
-                )";
-            echo "declared sed_command";
             sample_data="$( echo -e "${{ env.sample_data }}" | sed -E 's/"/\\"/g' )";
             echo "declared sample_data";
 
             var_0="$( jq -n '${sample_data}' | jq 'paths | length' )";
             echo "declared var_0='${var_0}'";
-            var_0="$( echo -e ${var_0} | sed -E "${sed_command}" || echo "SED COMMAND FAILED" )";
-            echo "::set-output name=var_0::${var_0}";
+            var_0="$( echo -e ${var_0} | jq -sRr @uri || echo "JQ URI ENCODE OUTPUT FAILED" )";
+            echo "var_0=${var_0}" >> $GITHUB_OUTPUT;
             echo "set var_0";
 
             var_1="$( jq -n '${sample_data}' | jq 'paths' )";
             echo "declared var_1='${var_1}'";
-            var_1="$( echo -e ${var_1} | sed -E "${sed_command}" || echo "SED COMMAND FAILED" )";
-            echo "::set-output name=var_1::${var_1}";
+            var_1="$( echo -e ${var_1} | jq -sRr @uri || echo "JQ URI ENCODE OUTPUT FAILED" )";
+            echo "var_1=${var_1}" >> $GITHUB_OUTPUT;
             echo "set var_1";
 
             var_2="$( jq -n '${sample_data}' | jq 'paths(scalars)' )";
             echo "declared var_2='${var_2}'";
-            var_2="$( echo -e ${var_2} | sed -E "${sed_command}" || echo "SED COMMAND FAILED" )";
-            echo "::set-output name=var_2::${var_2}";
+            var_2="$( echo -e ${var_2} | jq -sRr @uri || echo "JQ URI ENCODE OUTPUT FAILED" )";
+            echo "var_2=${var_2}" >> $GITHUB_OUTPUT;
             echo "set var_2";
 
             var_3="$( jq -n '${sample_data}' | jq 'to_entries' )";
             echo "declared var_3='${var_3}'";
-            var_3="$( echo -e ${var_3} | sed -E "${sed_command}" || echo "SED COMMAND FAILED" )";
-            echo "::set-output name=var_3::${var_3}";
+            var_3="$( echo -e ${var_3} | jq -sRr @uri || echo "JQ URI ENCODE OUTPUT FAILED" )";
+            echo "var_3=${var_3}" >> $GITHUB_OUTPUT;
             echo "set var_3";
 
             var_4="$( jq -n '${sample_data}' | jq '.' )";
             echo "declared var_4='${var_4}'";
-            var_4="$( echo -e ${var_4} | sed -E "${sed_command}" || echo "SED COMMAND FAILED" )";
-            echo "::set-output name=var_4::${var_4}";
+            var_4="$( echo -e ${var_4} | jq -sRr @uri || echo "JQ URI ENCODE OUTPUT FAILED" )";
+            echo "var_4=${var_4}" >> $GITHUB_OUTPUT;
             echo "set var_4";
 
-      - name: Check manual set-output
+      - name: Show manual variables
         uses: jadutter/jq-action@develop
         with:
           cmd: >
