updated workflow

diff --git a/.github/workflows/test-all.yml b/.github/workflows/test-all.yml
--- a/.github/workflows/test-all.yml
+++ b/.github/workflows/test-all.yml
@@ -95,51 +95,25 @@ jobs:
           sample_var_1="${{ env.sample_var_1 }}"
           sample_var_2="${{ env.sample_var_2 }}"
           sample_var_3="${{ env.sample_var_3 }}"
-          function encode(){
-            sed -E '
-              :nextLine;
-              # if not the end of the file
-              $!{
-                # add the next line to the pattern space
-                N;
-                # grab another line
-                b nextLine;
-              }
-              # escape backslash characters
-              s/\\/\\\\/g;
 
-              # escape percentage sign
-              s/%/%25/g;
-
-              # esape newline characters
-              s/\n/%0A/g;
-              s/\r/%0D/g;
-
-              # escape double quotes
-              s/\"/\\\"/g;
-
-              # escape dollar sign
-              s/\$/\\$/g;
-            '
-          }
           echo "declared variables";
 
-          esc_sample_var_0="$( echo "${sample_var_0}" | encode || echo "SED COMMAND FAILED")";
+          esc_sample_var_0="$( echo "${sample_var_0}" | ./encode.sh || echo "SED COMMAND FAILED")";
           echo "    sample_var_0:'${sample_var_0}'";
           echo "esc_sample_var_0:'${esc_sample_var_0}'";
           echo "sample_var_0=${esc_sample_var_0}" >> $GITHUB_OUTPUT;
 
-          esc_sample_var_1="$( echo "${sample_var_1}" | encode || echo "SED COMMAND FAILED")";
+          esc_sample_var_1="$( echo "${sample_var_1}" | ./encode.sh || echo "SED COMMAND FAILED")";
           echo "    sample_var_1:'${sample_var_1}'";
           echo "esc_sample_var_1:'${esc_sample_var_1}'";
           echo "sample_var_1=${esc_sample_var_1}" >> $GITHUB_OUTPUT;
 
-          esc_sample_var_2="$( echo "${sample_var_2}" | encode || echo "SED COMMAND FAILED")";
+          esc_sample_var_2="$( echo "${sample_var_2}" | ./encode.sh || echo "SED COMMAND FAILED")";
           echo "    sample_var_2:'${sample_var_2}'";
           echo "esc_sample_var_2:'${esc_sample_var_2}'";
           echo "sample_var_2=${esc_sample_var_2}" >> $GITHUB_OUTPUT;
 
-          esc_sample_var_3="$( echo "${sample_var_3}" | encode || echo "SED COMMAND FAILED")";
+          esc_sample_var_3="$( echo "${sample_var_3}" | ./encode.sh || echo "SED COMMAND FAILED")";
           echo "    sample_var_3:'${sample_var_3}'";
           echo "esc_sample_var_3:'${esc_sample_var_3}'";
           echo "sample_var_3=${esc_sample_var_3}" >> $GITHUB_OUTPUT;
